### ISSUE TITLE
Resource manifest

### ISSUE THREAD

**Issue by BigPoppi15** [citizenfx/fivem-docs#100]
both of the manifest links are 404

**Comment by glitchdetector** [comment]
Could you maybe provide some context? Like the lines and files where the incorrect links are?

**Comment by BigPoppi15** [comment]
Theses links
[image: YNW Melly _Dangerously In Love (772 Love Pt. 2)_ (Official Audio) -
YouTube - Google Chrome 4_6_2020 1_10_30 PM.png]

**Comment by nathanctech** [comment]
??
https://docs.fivem.net/docs/scripting-reference/resource-manifest/resource-manifest/ works fine?

When opening an issue you really need to be specific.

**Comment by BigPoppi15** [comment]
@Nathan C, not that link look at the blue text in my screen shot I sent!

**Comment by nathanctech** [comment]
You can't send screenshots to a github issue over email. Upload it somewhere and send a link to it if you must.

**Comment by BigPoppi15** [comment]
https://cdn.discordapp.com/attachments/688936982042247247/696771737521618974/YNW_Melly__Dangerously_In_Love_772_Love_Pt._2__Official_Audio_-_YouTube_-_Google_Chrome_4_6_2020_1_1.png
