### ISSUE TITLE
failed to transform "scss/main.scss" (text/x-scss)

### ISSUE THREAD

**Issue by chandanroksjsr** [citizenfx/fivem-docs#103]
Building sites … WARN 2020/04/09 20:50:29 found no layout file for "JSON" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Built in 5523 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_9fadf33d895a46083cdd64396b57ef68" not found in file cache

**Comment by blattersturm** [comment]
are you using hugo-extra?

**Comment by chandanroksjsr** [comment]
yes

**Comment by stannum-cfx** [comment]
Try an older hugo build like https://github.com/gohugoio/hugo/releases/tag/v0.60.1 for example. Make sure to get hugo_extended.

**Comment by chandanroksjsr** [comment]
sure i'll give it a try
