### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by rafa203gt** [citizenfx/fivem-docs#149]
good afternoon fivem, I wanted to ask you if you could fix this error that consists of the game not loading and the screen stays frozen...  

I get things like this:

![Captura de pantalla (9)](https://user-images.githubusercontent.com/66626151/84032981-79b13080-a998-11ea-870f-1edbb327e799.png)

**Comment by AteshM** [comment]
Wrong repo =)

**Comment by technetium-cfx** [comment]
Please head over to our [forums](https://forum.cfx.re/ )or [Discord](https://discord.gg/fivem) for support requests, GitHub is not the place for that.
