### ISSUE TITLE
FiveM Problem 

### ISSUE THREAD

**Issue by ThatGuyMax07** [citizenfx/fivem-docs#157]
![Capture](https://user-images.githubusercontent.com/68082237/87085226-1f083000-c1f5-11ea-910a-290950a3a685.PNG)
It is showing this every time I try to get in

**Comment by blattersturm** [comment]
Not a documentation issue.

**Comment by heybeton** [comment]
do u fix it? i have this problem too

**Comment by 000yesnt** [comment]
[Discrete GPU issue.](https://forum.fivem.net/t/solution-forcing-fivem-to-use-your-discrete-gpu-infinite-loading-fix/217731)
Ask in the forums next time.
