### ISSUE TITLE
Screen Glitch#159

### ISSUE THREAD

**Issue by TOTOBeleaua** [citizenfx/fivem-docs#159]
Hi guys, after that update on FiveM the game screen is buggy. I'm not the only one who has this problem. Can anyone help me?
![fivem](https://user-images.githubusercontent.com/68099369/87124344-4dd3e400-c291-11ea-9260-18a0819bac31.png)
PC SPECS: i7-9700,amd radeon r9 270 x,16 gb ram
WIN8.1 PRO,PC

I have friends who have a weaker PC than me and they can play.

**Comment by 000yesnt** [comment]
This is a repo for FiveM documentation, not client issues.
Ask in the forums.

**Comment by itIsMaku** [comment]
I have same issue, i don't know how to fix it. :/

**Comment by technetium-cfx** [comment]
Not a documentation issue. This Github repository is not for support questions. Please use the forums or Discord for that.

**Comment by wawewocooy** [comment]
https://imgur.com/undefined

Me to I tired How To Fix
