### ISSUE TITLE
Header not resizing on medium displays

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [citizenfx/fivem-docs#160]
Hey!

I was trying to look on the docs but the header navigation bar overflows/doesn't resize correctly (see screenshot)
![Screenshot 2020-07-11 at 21 30 27](https://user-images.githubusercontent.com/53900565/87232260-c3d56980-c3bd-11ea-9c25-876d525b0010.png)

My current screen size when breaking: 11 inch, just wanted to let you guys know of this problem.

 Have a nice rest of your day! Casper.

**Comment by technetium-cfx** [comment]
Thanks! That's indeed an issue in the current template. We're looking to align our documentation template with our new design soon though, so this should be resolved when we get around doing so. Closing this issue, as we won't fix the current template.
