### ISSUE TITLE
Vehicles not spawning properly - FiveM server

### ISSUE THREAD

**Issue by KingFilipek** [citizenfx/fivem-docs#162]
Hello, i would like some1 to help me out. So i have this problem with citizens not spawning properly in LS... Whenever i load the server the vehicles and peds don't spawn at most locations, at some points (it's always different) everything is good, but mostly the streets are empty. If i use NoClip and fly over the streets, highways,... i can see some 'silhoulettes' of vehicles, but as i try to come closer to them, they disapear.

I tried to reinstall my server twice to confirm it's not an issue in my server files (even on my other server this issue appers). I also reinstalled whole FiveM, but nothing helped. - It might be because i accidently deleted a 'FiveM game cache', i wanted to delete my server game cache, i had both files opened and i deleted the FiveM cache instead of the server one... i couldn't recover all files so i reinstalled the FiveM as i said, but... nothing helped.

I'll appriciate every help, thank you :))

**Comment by smallo92** [comment]
What in your brain made you think this was the right place to put this?
