### ISSUE TITLE
Blips mcdonalds

### ISSUE THREAD

**Issue by chriscyprus04** [citizenfx/fivem-docs#169]

**Comment by chriscyprus04** [comment]
mcdonalds

**Comment by arthur-rl** [comment]
What was the point of making this issue?

**Comment by MrMathias154** [comment]
just a dumbs guys a think ^^

**Comment by 000yesnt** [comment]
If this is _somehow_ an issue (blips not showing I assume?), go to the [Cfx.re/FiveM forums](https://forum.cfx.re/).
This Github repo is for _documentation_ for FiveM.
