### ISSUE TITLE
io.popen('php -v') not working in linux version

### ISSUE THREAD

**Issue by mamadlooloo** [citizenfx/fivem-docs#173]
Hello
[ All about the LUA ]
Why io.popen('php -v') not work in linux version???
In Windows version work perfectly, but in linux:
```lua
SCRIPT ERROR: @script_name/server.lua:line_number: 'popen' not supported
```
I want send some data from lua to node.js script (or php).
This code very important for me.
Thanks

**Comment by cerium-cfx** [comment]
This repository's issue section is not for your problems with scripting. Use appropriate channels such as the Cfx forum https://forum.cfx.re

**Comment by mamadlooloo** [comment]
This problem related to FiveM linux server files and no one can solve this except FiveM developers.
See error again please ->
```lua
SCRIPT ERROR: @script_name/server.lua:line_number: 'popen' not supported
```
```io.popen()``` is a native lua function and not working in linux version.

**Comment by eblio** [comment]
According to the [documentation of popen](https://www.lua.org/manual/5.1/manual.html#pdf-io.popen) : "This function is system dependent and is not available on all platforms.".

**Comment by mamadlooloo** [comment]
In Windows version of FiveM work perfectly, but in linux not at all.
@eblio
