### ISSUE TITLE
Error GTA5.exe!sub_1411EFE3C (0x1f4)

### ISSUE THREAD

**Issue by Andrea-98** [citizenfx/fivem-docs#194]
Last version GTA 5
Version OS Windows 10 pro build 2004
Legit game
Steam download

[Window Title]
Error GTA5.exe!sub_1411EFE3C (0x1f4)

[Main Instruction]
GTA5.exe!sub_1411EFE3C (0x1f4)

[Content]
An error at GTA5.exe!sub_1411EFE3C (0x1f4) caused FiveM to stop working. A crash report is being uploaded to the FiveM developers.

Legacy crash hash: don-papa-red
Stack trace:
  GTA5.exe!sub_1411EFE3C (0x1f4)
  0x690074006e0061
  0x61005700280020
  0x20007300650076
  0x6e0075006f0053
  0x69007200470064
  0x290064

[^] Nascondi dettagli  [Save information] [Chiudi]

[Expanded Information]
Crash signature: fivem.exe+11F0030
Report ID: si-c9ee36ccbf9745bb88bda8bebf2103f7
You can press Ctrl-C to copy this message and paste it elsewhere.

[CfxCrashDump_2020_10_20_11_49_46.zip](https://github.com/citizenfx/fivem-docs/files/5408425/CfxCrashDump_2020_10_20_11_49_46.zip)

**Comment by blattersturm** [comment]
This isn't a docs issue, what?
