### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by AnishRaj10** [citizenfx/fivem-docs#196]
I have Reinstalled FiveM several times still it's not working. This is how my FiveM looks when I open it, there is no server option and even I download FiveM from https://fivem.net/ still the older version pop-ups. Please help
![Screenshot (142)](https://user-images.githubusercontent.com/73380820/97070423-bc953d00-15f5-11eb-8958-1c780a1dd1fa.png)

**Comment by technetium-cfx** [comment]
This is not the place to submit issues. Reinstalling doesn't help. Please use our forums or Discord for support.
https://forum.cfx.re/t/solution-forcing-fivem-redm-to-use-your-discrete-gpu-infinite-loading-fix/217731
