### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Vtkush** [citizenfx/fivem-docs#205]
Hello.

Im having an issue with Fivem and Account.

One day I logged into my friend steam account and played FiveM, on the next day I loggend into my original account and linked all my accounts( steam,fivem,discord,xbox) on FiveM, but the game still saying that Im logged on my friend account. 

When I try to log on a server,m I log with my friend datas.

**Comment by technetium-cfx** [comment]
Please use our [forums](https://forum.cfx.re/) or [Discord](https://discord.gg/fivem) for support questions.
