### ISSUE TITLE
stuck on the main gta 5 loading screen

### ISSUE THREAD

**Issue by topsidewolf697** [citizenfx/fivem-docs#206]
hi i am stuck on the main gta 5 loading screen i don't know what to do. it has never done this before
![7](https://user-images.githubusercontent.com/74986376/100140436-db068680-2e88-11eb-985e-9409ee1bedb8.PNG)

**Comment by technetium-cfx** [comment]
Please use our [forums](https://forum.cfx.re/) or [Discord](https://discord.gg/fivem) for support questions.
