### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Barbywrld** [citizenfx/fivem-docs#208]
My perms are not working for my server i have tried to get other people to help, It would be nice if i could get help with it.

**Comment by AvarianKnight** [comment]
That's what the forums are for, this isn't the place for support.

**Comment by Barbywrld** [comment]
> That's what the forums are for, this isn't the place for support.

oh i didn't know but can we call on discord and you try and fix it bc i have had people look at it

**Comment by AvarianKnight** [comment]
> That's what the forums are for, this isn't the place for support.
