### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by JackHofflol** [citizenfx/fivem-docs#210]
hello ive been playing fivem for a while every time there is an update i get an error code [
![image](https://user-images.githubusercontent.com/76009422/102126048-8cf5fa80-3e18-11eb-99c9-12c26fd59833.png)
](url) this has been happening for so long the only way someone told me to fix it is to keep trying to download it and im tired of doing it it takes 3 hours of me clicking please let me know hot to fix it

**Comment by nathanctech** [comment]
Please do not use github for support. Discord exists.

**Comment by technetium-cfx** [comment]
Step one in fixing your issue is to join our [Discord](https://discord.gg/fivem) or [forums](https://forum.cfx.re) and ask your question there. This is not the place for support.
