### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Tonypaka** [citizenfx/fivem-docs#216]
อยู่ดีๆผมก็โดนเเบนอย่างไม่ทราบสาเหตุผมเล่นเหมือนคนปกติทั่วไปเเท้ๆT-T
![image](https://user-images.githubusercontent.com/76524717/103002828-35673580-4562-11eb-80a3-fd38c6dc5c0b.png)

**Comment by AvarianKnight** [comment]
Nice.

**Comment by Tonypaka** [comment]
> ดี.

ดีสิโดนเเบนทั้งที่ผมยังไม่ทำไรเลย

**Comment by Tonypaka** [comment]
![image](https://user-images.githubusercontent.com/76524717/103003481-714eca80-4563-11eb-9cd8-c8756de5bc40.png)
I begged to help me. I was playing with normal people, but why would I get hit?

**Comment by Tonypaka** [comment]
Please consider and investigate.

**Comment by technetium-cfx** [comment]
This is not the place for support.

**Comment by Tonypaka** [comment]
Where can I go to the tap?
