### ISSUE TITLE
Bans FAQ

### ISSUE THREAD

**Issue by lionpetros** [citizenfx/fivem-docs#222]
@balika011 @thers @Vaksdk @thrasherht  @tabarra Good evening and happy new year always in good health for a few days now i cant play five m he has been telling me that i cant go in until the original ban is gone that is i ate global but im really completely clean i do not know the reason i ate a ban i will ask you if you van take it out is the only game i play my discord name is LION_Petros#4449 my pleasure to contact and from there also my steam name is LIONPETROS please take it out as soon as possible i have time to play and i very much and my e-mail is pestlikesp81@gmail.com

**Comment by AvarianKnight** [comment]
Does this look like a support forum?

**Comment by technetium-cfx** [comment]
Stop eating bans!

**Comment by lionpetros** [comment]
where to send to help me??
