### ISSUE TITLE
Warning: 'onesync' is read only. Try using `+set onesync` in the command line.

### ISSUE THREAD

**Issue by draobrehtom** [citizenfx/fivem-docs#229]
In documentation about **Setting up a server (https://docs.fivem.net/docs/server-manual/setting-up-a-server/)** it says to use `set onesync on` in server.cfg.

When you follow documentation, you get following warning:
> Warning: 'onesync' is read only. Try using `+set onesync` in the command line.

**Comment by blattersturm** [comment]
Yeah, a warning. Still sets fine.

**Comment by draobrehtom** [comment]
@blattersturm 
Well, on my side it doesn't set fine :/

**Comment by draobrehtom** [comment]
![изображение](https://user-images.githubusercontent.com/6503721/104772682-18dea780-5774-11eb-9e22-7272063b1485.png)
