### ISSUE TITLE
Example cfg not redirecting to example cfg page

### ISSUE THREAD

**Issue by Ruqen** [citizenfx/fivem-docs#248]
**To reproduce**

Go to: https://docs.fivem.net/docs/server-manual/setting-up-a-server/
Press: ![image](https://user-images.githubusercontent.com/73693641/119403821-9c427380-bce7-11eb-9ecc-9ceca2578b87.png)

**Expected result**
You will be in the example cfg page.

**Actual result**
Nothing happens.

**Comment by technetium-cfx** [comment]
Fixed by #250
