### ISSUE TITLE
Doc todo: add playerJoining event

### ISSUE THREAD

**Issue by tabarra** [citizenfx/fivem-docs#275]
Currently the event `playerJoining` is not documented.  
Reference: https://github.com/citizenfx/fivem/blob/b2fa00120d0e3d8a61a360baf1c3c47eb4c20968/code/components/citizen-server-impl/src/ClientRegistry.cpp#L183  
  
this is a simple one but I can't commit right now, so just adding an issue to not forget this.

**Comment by blattersturm** [comment]
It is documented however: 

https://docs.fivem.net/docs/scripting-reference/events/server-events/#playerjoining

**Comment by tabarra** [comment]
In this case, this page is deprecated: https://docs.fivem.net/docs/scripting-reference/events/list/
