### ISSUE TITLE
Issues per last update

### ISSUE THREAD

**Issue by roentgenium-cfx** [citizenfx/fivem-docs#305]
Some formatting issues that may need some new line breaks, for instance here: https://docs.fivem.net/docs/server-manual/setting-up-a-server-txadmin/ (scroll down for a while - you will see!)

Some new headers might be ideal
![image](https://user-images.githubusercontent.com/87940610/155855764-7bcfdde7-cd6e-4934-a610-61ebc22bac9b.png)

The following link sections don't lead anywhere - will need content or for us to back out changes.
![image](https://user-images.githubusercontent.com/87940610/155855903-c57f2070-77ab-45f1-8a04-486fb7b3d665.png)

![image](https://user-images.githubusercontent.com/87940610/155855891-9655ee27-4d66-42ff-9f4f-09db1fa5adf2.png)

**Comment by PsychoShock** [comment]
> Some new headers might be ideal

This should be fix:
![image](https://github.com/citizenfx/fivem-docs/assets/94499608/956bce0f-1877-4e96-9ea1-9c5c73be29a0)

> The following link sections don't lead anywhere - will need content or for us to back out changes.

This should be fix with https://docs.fivem.net/docs/#server-owners


This issue can mostly be closed @4mmonium
