### ISSUE TITLE
Heading overlaps the links above it

### ISSUE THREAD

**Issue by SQKo** [citizenfx/fivem-docs#327]
For example in https://docs.fivem.net/docs/ I cannot click on the "start a server" or "resources" link due to the next heading overlaps it

Using Firefox (in inspect element) we can see the area covered
![anchorblock](https://user-images.githubusercontent.com/87897282/167308701-9b812ef3-075c-4b13-9662-631385721063.png)

same behavior in chrome

The css rule `.docContent [id]:before` seems to be the cause

**Comment by blattersturm** [comment]
Should be fixed now!
