### ISSUE TITLE
Boilerplate download issue

### ISSUE THREAD

**Issue by Joonabb** [citizenfx/fivem-docs#332]
https://docs.fivem.net/docs/scripting-manual/using-scaleform/#boilerplate seems to be in a codeblock, instead of downloadable.

**Comment by 4mmonium** [comment]
> https://docs.fivem.net/docs/scripting-manual/using-scaleform/#boilerplate seems to be in a codeblock, instead of downloadable.

Thank you for pointing this out, I'll resolve it soon.
