### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by asge2810** [citizenfx/fivem-docs#345]
Hey My name is Asger. I have a BIG problem, i tried cheating in FiveM, but i have stopped, i dont do it anymore it was a mistake.
I got banned in 14 days, and when i checked how many days there was left it said 250 days, why is that.
I am very sad that i got banned that long can you do something about it Please, im very sorry!

**Comment by asge2810** [comment]
My ban id if you need it 31f59b95-d18f-42d6-891e-e64a48da9eb7
:(

**Comment by FuseWasTaken** [comment]
iq issue.

**Comment by asge2810** [comment]
Im sorry what?

**Comment by neptunium-cfx** [comment]
This is not a place for ban appeals, nor you won't be unbanned - wait it out.

**Comment by blattersturm** [comment]
i'm confused
