### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by vmx4** [citizenfx/fivem-docs#357]
#356 

fix fivem updating game storage stuck

**Comment by vmx4** [comment]
![Desktop Screenshot 2022 10 27 - 13 43 25 29 (2)](https://user-images.githubusercontent.com/116824068/198326292-cf7e1c4f-cafe-4ff4-b565-49505ef2721d.png)

**Comment by nihonium-cfx** [comment]
We are aware of the issue and working hard to fix it, but this is not the place for support questions.
