### ISSUE TITLE
Invalid Pastebin link | REMOVE_IPL

### ISSUE THREAD

**Issue by cedriclmao** [citizenfx/fivem-docs#358]
Hi,

The pastebin link from the REMOVE_IPL native is invalid.
https://docs.fivem.net/natives/?_0xEE6C5AD3ECE0A82D

**Comment by 4mmonium** [comment]
> Hi,
> 
> The pastebin link from the REMOVE_IPL native is invalid. https://docs.fivem.net/natives/?_0xEE6C5AD3ECE0A82D

Thanks for reporting list. I made a list of all missing pastebin links, and will be on it this week.

- SET_RADIO_TO_STATION_NAME
- SET_VEH_RADIO_STATION
- GET_TIMECYCLE_MODIFIER_INDEX
- GET_HUD_COLOUR
- REPLACE_HUD_COLOUR
- REPLACE_HUD_COLOUR_WITH_RGBA
- SET_MINIMAP_COMPONENT
- SET_MP_GAMER_TAG_HEALTH_BAR_COLOUR
- TERMINATE_ALL_SCRIPTS_WITH_THIS_NAME
- CREATE_AMBIENT_PICKUP
- CREATE_PICKUP
- CREATE_PICKUP_ROTATE
- CREATE_PORTABLE_PICKUP
- DOES_PICKUP_OF_TYPE_EXIST_IN_AREA
- REMOVE_ALL_PICKUPS_OF_TYPE
- REMOVE_IPL
- START_NEW_SCRIPT

**Comment by PsychoShock** [comment]
This can be closed since it was "fix" on the native docs.

**Comment by Mathu-lmn** [comment]
@cedriclmao you can close this :)
