### ISSUE TITLE
Add Qbox to the list of frameworks

### ISSUE THREAD

**Issue by sebinmichael** [citizenfx/fivem-docs#465]
As the title says, Qbox is an upcoming framework which should be added to the list of frameworks in the documentation.
Qbox: https://github.com/Qbox-project
Frameworks page: https://docs.fivem.net/docs/server-manual/frameworks/

**Comment by AvarianKnight** [comment]
Given the churn around frameworks and whats constantly being considered "the best" or "the worst" is it even a good idea to have any of these in the docs?

**Comment by PsychoShock** [comment]
You can check my [PR](https://github.com/citizenfx/fivem-docs/pull/420), this include Qbox.

> Given the churn around frameworks and whats constantly being considered "the best" or "the worst" is it even a good idea to have any of these in the docs?

This page is not really to show what's the "best" or "worst" framework but just a page for CFX to show some "support" of the currents frameworks still supported and facilited the new devs to discover new frameworks.

**Comment by sebinmichael** [comment]
> Given the churn around frameworks and whats constantly being considered "the best" or "the worst" is it even a good idea to have any of these in the docs?

Its not meant to show the best or the worst, just to mention the list of known frameworks alphabetically to help those who are new.

> This page is not really to show what's the "best" or "worst" framework but just a page for CFX to show some "support" of the currents frameworks still supported and facilited the new devs to discover new frameworks.

+1

> You can check my [PR](https://github.com/citizenfx/fivem-docs/pull/420), this include Qbox.

Hi, I hadn't seen this. Thank you.

**Comment by sebinmichael** [comment]
Revised status.

**Comment by sebinmichael** [comment]
Revised status.

**Comment by sebinmichael** [comment]
> Given the churn around frameworks and whats constantly being considered "the best" or "the worst" is it even a good idea to have any of these in the docs?

Its not meant to show the best or the worst, just to mention the list of known frameworks alphabetically to help those who are new.

> This page is not really to show what's the "best" or "worst" framework but just a page for CFX to show some "support" of the currents frameworks still supported and facilited the new devs to discover new frameworks.

+1

> You can check my [PR](https://github.com/citizenfx/fivem-docs/pull/420), this include Qbox.

Hi, I hadn't seen this. Thank you.

**Comment by sebinmichael** [comment]
> Given the churn around frameworks and whats constantly being considered "the best" or "the worst" is it even a good idea to have any of these in the docs?

Its not meant to show the best or the worst, just to mention the list of known frameworks alphabetically to help those who are new.

> This page is not really to show what's the "best" or "worst" framework but just a page for CFX to show some "support" of the currents frameworks still supported and facilited the new devs to discover new frameworks.

+1

> You can check my [PR](https://github.com/citizenfx/fivem-docs/pull/420), this include Qbox.

Hi, I hadn't seen this. Thank you.
