### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by Aidoodle** [citizenfx/fivem-docs#74]
A component of your computer is preventing you from being able to play FiveM. Please remove any unused network cards installed in your computer to be able to play FiveM.
The associated correlation ID is c8902c37-705c-4794-be5e-c5e172b59607_01.

HELP ME !!! T_T

**Comment by nimoalr** [comment]
Are you retarded? Why the fuck do you create an issue on the doc repo for something that isn't related at all ? Can't you just use your brain, read and do what the message says?
