### ISSUE TITLE
How you can help | BAN

### ISSUE THREAD

**Issue by TigerTigerov** [citizenfx/fivem-docs#77]
Hi, I got a global ban on FiveM and I would like to know why I got it and whether it can be removed
ban id: e8f0a814-2e08-4425-b119-4a8dcec0b94e_38

**Comment by nathanctech** [comment]
In what universe did you think posting about a ban on a repository about documentation was a good idea?

**Comment by SNIKRS** [comment]
Suck my dick fivem, u brain dead u dont even know how to dev well a fucking shitty framework. Life to CaliforniaRP.

**Comment by SNIKRS** [comment]
JOIN CALIFORNIARP : discord.gg/california

**Comment by CaliforniaFiveM** [comment]
wtf

**Comment by CaliforniaFiveM** [comment]
stop advertising our server

**Comment by Riziebtw** [comment]
YEAH NIGGA ASS JOIN CALIFORNIA: discord.gg/california

**Comment by CaliforniaFiveM** [comment]
omg

**Comment by Riziebtw** [comment]
CALIFORNIARP DEVELOPERS > FIVEM DEVELOPERS

**Comment by SNIKRS** [comment]
![image](https://user-images.githubusercontent.com/29042883/73365803-296ce800-42ad-11ea-98a0-76794a570c34.png)
KORIOZZZZZZZZZ

**Comment by Deliux** [comment]
CaliM

**Comment by SNIKRS** [comment]
AYMAN CALIFORNIA LE PLUS BOOOOOOOO
![image](https://user-images.githubusercontent.com/29042883/73365837-3c7fb800-42ad-11ea-8d78-98801fe9f78b.png)

**Comment by CaliforniaFiveM** [comment]
Dox SNIKRS

Prénom/Nom : Lorenzo Agius
Âge : 18 ans
Date de naissance : 03/01/2002
Numéro de téléphone : (+33) 07 89 57 73 93
Ville/Adresse : Poitiers

IP :
Twitter : @snikrsoff
Instagram : @snikrsoff

Discord :
- SNIKRS.#0001 (compte actuel)
- SNIKRS#4689 (deuxième compte)

Steam :
- Lorenzo Moristocratte (deuxième compte)
- SNIKRS ou ?????? (compte actuel)

adresse email : xteaw.pro@gmail.com (il en a d'autres)

Nouveau lien de son serv discord: http://discord.gg/santosroleplay

**Comment by Riziebtw** [comment]
nikmouk california

**Comment by NobodyFX** [comment]
Dox SNIKRS

Prénom/Nom : Lorenzo Agius
Âge : 18 ans
Date de naissance : 03/01/2002
Numéro de téléphone : (+33) 07 89 57 73 93
Ville/Adresse : Poitiers

IP :
Twitter : @snikrsoff
Instagram : @snikrsoff

Discord :
- SNIKRS.#0001 (compte actuel)
- SNIKRS#4689 (deuxième compte)

Steam :
- Lorenzo Moristocratte (deuxième compte)
- SNIKRS ou ?????? (compte actuel)

adresse email : xteaw.pro@gmail.com (il en a d'autres)

Nouveau lien de son serv discord: http://discord.gg/santosroleplay

**Comment by NobodyFX** [comment]
Beh alors snikrs

**Comment by NobodyFX** [comment]
Arrete de faire le pro stp jvais te mettre en pls toi et tes suceurs qui mettent tous des pp hackerman pour faire les hacker

**Comment by SNIKRS** [comment]
Mooooh fdp on a un dox complet sur vous pk vous faites les mecs

**Comment by NobodyFX** [comment]
if you can delete the comment form snikrs cause its a doxx of a friend @cerium-cfx thx

**Comment by SNIKRS** [comment]
u just dropped a dox on me but ok lol

**Comment by NobodyFX** [comment]
bref ton doxx j'men blc juste arrete de faire le fou pck tu sais pas ce qu'on peut faire donc reste dans ton coin et on restera nous aussi dans notre coin mais évite de venir vers nous chercher la merde

**Comment by SNIKRS** [comment]
MDrrrr gros fils de pute jvous ai jamais parler vous etes la a ddos mon serv depuis 3 mois
mtn viens dm discord ptite salope

**Comment by NobodyFX** [comment]
beh toi vien dm mdrr

**Comment by SNIKRS** [comment]
Les ptit francais qui font les fous sur fivem ca me fais taper des barres

**Comment by SNIKRS** [comment]
SNIKRS#0001

**Comment by NobodyFX** [comment]
et si jamais c pas nous qui font les ddos mdrrr mais on le connait très bien et j'vais pas l'empecher de ddos une ptite pute comme toi

**Comment by SNIKRS** [comment]
suce mon chibrax
