### ISSUE TITLE
Client FAQ

### ISSUE THREAD

**Issue by jonathonbarton** [citizenfx/fivem-docs#88]
Q: How do I switch back and forth between playing on FiveM servers and regular Rockstar GTA:O play? Do I have to choose one or the other? Is FiveM counted by R* as a mod? **Will having FiveM installed get me banned in GTA:O**?

A: (I dunno, I've looked and looked and not found the answer - not even in the FAQ...)

**Comment by Zeemahh** [comment]
What? This isn't a place to ask these questions, this is a place for issues regarding the docs. FiveM and GTA:O are totally separate.

**Comment by jonathonbarton** [comment]
It's an issue in the docs because it's a frequently asked question that isn't answered in the FAQ.
It's a missing documentation issue.

**Comment by nathanctech** [comment]
The answer is no, you will not be banned. The game doesn't touch your GTA V install and you can freely play both.

**Comment by cerium-cfx** [comment]
This is already listed on our main website that users visit before downloading the client https://fivem.net/#no-bans

You're more than welcome to PR anything to the docs and we will take a look, but please use the forum or Discord in the future if you cannot find answers to questions.
