### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by NamaHus** [citizenfx/fivem-docs#92]
when I try to join Hidden Life Server,
It gets stuck at some point 

it works at other servers but Hidden Life only.

plz help.

![Annotation 2020-03-19 202938](https://user-images.githubusercontent.com/62396953/77096408-5e312c00-6a20-11ea-8daf-f3428391f36a.jpg)

**Comment by Rubylium** [comment]
Totally not an FiveM Client issue, but server issue.

**Comment by Something-Debug** [comment]
Seek help on the forums (forum.cfx.re) or the discord (discord.gg/fivem)

**Comment by fibonacci10** [comment]
> Totally not an FiveM Client issue, but server issue.

hey bro ,
All people can access the server. As for this person can not enter the problem from fivem

**Comment by manups4e** [comment]
who cares.. this is not a FiveM problem.. ask your server owners why it happens.. for sure GitHub IS NOT the place to talk about it.. nor this repository as this is just a bunch of stock resources

**Comment by cerium-cfx** [comment]
GitHub Issues is not for some FiveM issue. Only for issues/requests regarding this repository. Use the forum instead.
