### ISSUE TITLE
Running using FXServer.exe instead of run.cmd causes resources using fxmanifest.lua to fail to load.

### ISSUE THREAD

**Issue by cbzink** [citizenfx/fivem-docs#93]
Commit 27f379ba036ed929c86b593d1d98e341e3088c6e changed the guidance in _Setting up a server_ to run `FXServer.exe` instead of `run.cmd`.

This causes resources that use `fxmanifest.lua` manifest files rather than the deprecated `__resource.lua` manfiest to fail to load.

**Comment by cbzink** [comment]
Example output from running using `FXServer.exe`:

```
Found new resource test_res in D:/FXServer\server-data/resources//[local]/test_res
Resource loading for test_res failed:
Could not open resource metadata file citizen:/scripting/lua/json.lua
```

Running using `run.cmd` works as expected.

**Comment by blattersturm** [comment]
The server does not even bundle a file called `run.cmd` since the associated server build, and this doesn't reproduce.
